\LoadClass[11pt,a4paper]{report}

\usepackage[portuguese]{babel}
\usepackage[utf8]{inputenc}
\usepackage{aeguill}
\usepackage{graphicx}
\usepackage{tikz}
\usepackage[T1]{fontenc}
\usepackage{tgbonum}
\usepackage{multicol}
\usepackage[hidelinks]{hyperref}
\usepackage{xcolor}
\usepackage{lipsum}
\usepackage{titlesec, blindtext, color}
\definecolor{gray75}{gray}{0.75}
\newcommand{\hsp}{\hspace{20pt}}


%% Format the chapter titles and spacing
\titleformat{\chapter}[hang]{\Huge\bfseries}{\thechapter\hsp\textcolor{gray75}{|}\hsp}{0pt}{\Huge\bfseries}